socialblade/accounts/urls.py
from django.urls import path
from django import urls
from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('profile/', views.profile, name='accounts')

]

socialblade/home/urls.py
from django.urls import path
from django import urls
from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView

urlpatterns = [
     path('', views.index, name='index'),

]

socialblade/socialblade/urls.py
from django.urls import path, include

from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path("users/", include("django.contrib.auth.urls")),  # new
    path("users/", include("users.urls")),  # new
    path("accounts/", include("accounts.urls")),  # new


    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

socialblade/users/urls.py
from django.urls import path
from django import urls
from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView

urlpatterns = [
     path('login/', LoginView, {'template_name': 'users/login.html'}, name = 'login'),
     url('signup/',views.signup, name = 'signup'),
     url('posts/',views.posts, name = 'posts'),
     url('postform/',views.postform, name = 'postform'),


]

socialblade/accounts/models.py
from django.db import models

# Create your models here.

socialblade/home/models.py
from django.db import models

# Create your models here.

socialblade/users/models.py
from distutils.command.upload import upload
from django.db import models
from django.forms import CharField, ImageField
from django.forms.fields import DateTimeField
from matplotlib import image
from sqlalchemy import true
from django.contrib import admin
from django.conf import settings # needed for importing author function

# Create your models here.

class Post(models.Model):
        
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE, null=True
    )
    # include title 
    title = models.CharField(null=True, max_length=50)
    
#needs to be made optional blank = True must change jina loging to if single_post_img then post else skip
    image = models.ImageField(upload_to='images/', null = True) 

    quote = models.TextField(null=True)

    date = models.DateTimeField(auto_now_add=True, null=True)

socialblade/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )


 
 
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

        

socialblade/accounts/views.py
from django.shortcuts import render

# Create your views here.
# this page is where the login page sends you. 
# Create a bio with a picture you can change 
# all your uploads/post 

from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from matplotlib.style import context
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required()
def profile(request):

    return render(request, 'profile.html' )

socialblade/home/views.py
from django import views
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from matplotlib.style import context
from matplotlib.style import context
from django.views.generic import *


# Create your views here.
def index(request):
   
    return render(request, 'index.html')

socialblade/users/views.py
from django.contrib.auth import login, authenticate
from django import forms
from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from requests import post, request
from users.forms import SignUpForm
from matplotlib.style import context
from django.http import HttpRequest, HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from users.models import Post

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)# was UserCreationForm
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('login')  #profile
    else:
        form = SignUpForm() #was UserCreationForm
    return render(request, 'signup.html', {'form': form})


#displays post from users

def posts(request):
    userpost = Post.objects.all()
    return render(request, 'posts.html', {'userpost': userpost})


from .forms import PostForm
@login_required()
def postform(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PostForm(request.POST, request.FILES) 
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            form.save()

            form.errors
            return HttpResponseRedirect('/users/posts/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PostForm()

    return render(request, 'postform.html', {'form': form})

socialblade/accounts/templates/profile.html
<head>
  <title>Social blade</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<script src="https://cdn.tailwindcss.com"></script>

</head>
<h2 class="text-3xl font-bold underline"> Welcome {{ request.user.username }}</h2>
<br>
<br>
<div style="text-align: center;">

</div>
 
<div class="container-fluid text-center">
  <h1>Social Blade</h1>
  <p>welcome</p>

  <ul class="breadcrumb">
    <li><a href="{% url 'index' %}">Home</a></li>
    <li class="active">
      <a href="{% url 'posts' %}">View the latest Post</a> 
    </li>        
  </ul>
  </div>


<div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl">
    <div class="md:flex">
      <div class="md:shrink-0">
        <img class="h-48 w-full object-cover md:h-full md:w-48" src="https://w7.pngwing.com/pngs/298/243/png-transparent-email-address-computer-icons-mail-miscellaneous-angle-triangle-thumbnail.png" alt="create post">
      </div>
      <div class="p-8">
        <div class="uppercase tracking-wide text-sm text-indigo-500 font-semibold">Your post will appear here</div>
        <a href="{% url 'postform' %}" class="block mt-1 text-lg leading-tight font-medium text-black hover:underline">Create new post</a>
      </div>
    </div>
  </div>

socialblade/home/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Social blade</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid text-center">
  <h1>Social Blade</h1>
  <p>welcome</p>

  <ul class="breadcrumb">
    <li><a href="#">Home</a></li>
    <li><a href="{% url 'signup' %}">Sign Up</a></li>
    <li class="active">
      <a href="{% url 'posts' %}">View the latest Post</a> 
    </li>        
  </ul>
  </div>

socialblade/users/templates/postform.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  <style>
    form{
        text-align: center;
    }
</style>
</head>

<body>
<div class = "container lg-6">
<div class = "form-group">

<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <br>
    <p><label for="id_author">Author:</label> <select name="author" required="" id="id_author">
  <option value="" selected="">---------</option>

  <option value="1">brandon</option>

  <option value="6">cheybabe</option>

</select></p>
<p><label for="id_title">Title:</label> <input type="text" name="title" maxlength="50" required="" id="id_title" class="form-control"></p>
<p><label for="id_image">Image:</label> <input type="file" name="image" accept="image/*" required="" id="id_image" class="form-control"></p>
<p><label for="id_quote">Quote:</label> <textarea name="quote" cols="40" rows="10" required="" id="id_quote" class="form-control"></textarea></p>
    <input type="submit" value="Submit">
</div>
</form>


</div>
</body>

    
   
    

socialblade/users/templates/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<style>
  img{
    size: 300px;
    height: 300px;
    border-radius: 20px;
  }
</style>
<body>

<div class="container-fluid p-5 bg-primary text-white text-center">
  <h1>post</h1>
  <p></p> 
</div>

<div class="container mt-5">
  <div class="row">
  <div class="col-sm-6">
      {% for single_post in userpost %}
      <div class="card-header">
        <!-- remove if stataments if code does not work-->
      {{ single_post.quote }}
      <br>
      <a href=""><img src="{{ single_post.image.url }}"></a>
              </div>
      <div class="card-body">
  
      </div>
      </div>
      
      </div>
      <div class="col-sm-6">
      <em>
      {{ single_post.date }} {{ single_post.author }}
      </em>
      {% endfor %}
    </div>
  </div>
</div>

</body>
</html>

socialblade/users/templates/signup.html
<head>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>

<!-- Popper JS -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
<link rel="stylesheet" href=
"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />

<link rel="stylesheet" href=
"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity=
"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
        crossorigin="anonymous">

<style>
body {
  backdrop-filter: blur(20px);
  background: rgb(63,94,251);
background: radial-gradient(circle, rgba(63,94,251,1) 0%, rgba(252,70,107,1) 100%);
}

</style>

</head>
<title>Sign Up</title>

{% block content %}

<div class="container">
<div class="col-sm-6 text-center">
  <div class="card-body">

  <form method="post">
    {% csrf_token %}

    <div class="form-group justify-content-center">
   First Name:<br>

   <div class="form-group lg-3" >
   <input name="first_name" type="name" class="form-control">
   </div>
   <br>
   Last Name:<br>
   <div class="form-group">
   <input name="last_name" type="name" class="form-control">
   </div>
    <br>
    Username: <br>
    <div class="form-group">
    <input name="username" type="name" class="form-control">
    </div>
    <br>
    Email: <br>
    <div class="form-group">
    <input name="email" type="email" class="form-control">
    </div>
    <br>
    Create your password: <br>
    <div class="form-group">
    <input name="password1" type="password" class="form-control">
    
    </div>
    <br>
    Confirm your password: <br>
    <div class="form-group">
    <input name="password2" type="password" class="form-control" >

    </div>
      <br>
    <button type="submit" class="btn btn-primary btn-lg">Sign up</button>
  </form>
</div>
</div>
</div>
</div> 

{% endblock %}